1732545906512	Sync.LogManager	DEBUG	Flushing file log
1732545906513	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1732545906517	Sync.LogManager	DEBUG	Log cleanup threshold time: 1731681906517
1732545906521	Sync.LogManager	DEBUG	Done deleting files.
1732545932251	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1732545932251	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1732545932252	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1732545932256	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732545932278	Sync.SyncScheduler	DEBUG	Woke from sleep.
1732545932278	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732545936175	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732545937516	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732545941541	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1732545941541	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1732545941545	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732545941547	Sync.Service	DEBUG	User-Agent: Firefox/134.0a1 (Linux x86_64) FxSync/1.136.0.20241118092854.desktop
1732545941547	Sync.Service	INFO	Starting sync at 2024-11-25 15:45:41 in browser session nAwwJaw3LDsg
1732545941547	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1732545941549	Sync.Status	INFO	Resetting Status.
1732545941549	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1732545941549	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1732545941565	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/264523642/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1732545941565	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1732545941565	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1732545941565	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1732545941565	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1732545941568	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
